version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticket_system_app
    ports:
      - "${APP_PORT}:9000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - app-network

  mysql:
      image: mysql:8.0
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
      networks:
        - app-network


networks:
  app-network:
    driver: bridge
    name: ticketsystem_app-network
