services:


  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - ./todo:/var/www/html
    ports:
      - 8000:80

  mysql_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306